// クリップボード履歴（基盤層）。
// UI の形（ポップアップ / パネル / メニュー）は後で決めるため、ここでは
// データモデル・監視・永続化・呼び出し API だけを用意する。表示側はこの
// ObservableObject を購読するだけでよい。
//
// プライバシー方針（AGENTS.md の原則に従う）:
// - 既定はオフ。明示的に有効化したユーザーだけ記録する。
// - 保存先はローカルの Application Support のみ（ディレクトリ 0700 / ファイル 0600）。
//   内容をログ・エラー・標準出力に出さない。
// - パスワードマネージャ等が付ける concealed / transient 型のコピーは記録しない。
// - 1 件あたりの上限サイズと件数上限を設け、無制限に溜めない。

import AppKit
import Foundation

/// 履歴 1 件。
struct ClipEntry: Identifiable, Codable, Equatable {
    let id: UUID
    let text: String
    let copiedAt: Date

    /// メニューやリスト表示用の一行プレビュー（空白を畳んで先頭だけ）。
    var preview: String {
        let collapsed = text
            .split(whereSeparator: { $0.isNewline || $0 == "\t" })
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ⏎ ")
        let limit = 60
        if collapsed.count <= limit { return collapsed }
        return String(collapsed.prefix(limit)) + "…"
    }

    /// 文字数（表示用）。
    var characterCount: Int { text.count }
}

@MainActor
final class ClipboardHistory: ObservableObject {
    static let shared = ClipboardHistory()

    /// 選べる件数上限（設定 UI と揃える）。
    static let maxEntriesOptions = [20, 50, 100]
    /// 1 件あたりの上限（これを超えるテキストは記録しない）。巨大なコピーで
    /// 履歴ファイルが膨らむのを防ぐ。
    static let maxEntryLength = 100_000

    @Published private(set) var entries: [ClipEntry] = []

    /// 監視の ON/OFF。既定はオフ。
    var isEnabled: Bool {
        get { UserDefaults.standard.bool(forKey: "historyEnabled") }
        set {
            UserDefaults.standard.set(newValue, forKey: "historyEnabled")
            objectWillChange.send()
            newValue ? start() : stop()
        }
    }

    /// 件数上限。
    var maxEntries: Int {
        get {
            let v = UserDefaults.standard.integer(forKey: "historyMaxEntries")
            return Self.maxEntriesOptions.contains(v) ? v : 50
        }
        set {
            UserDefaults.standard.set(newValue, forKey: "historyMaxEntries")
            objectWillChange.send()
            trimAndSave()
        }
    }

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    /// 記録しないペーストボード型。パスワードマネージャ等が「履歴に残すな」の
    /// 意味で付ける事実上の標準（nspasteboard.org）。
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private init() {
        load()
    }

    // MARK: - 監視

    /// 有効なら監視を始める（起動時に呼ぶ）。
    func startIfEnabled() {
        if isEnabled { start() }
    }

    private func start() {
        guard timer == nil else { return }
        // macOS にはクリップボード変更通知が無いため changeCount をポーリングする。
        // 0.5 秒間隔なら体感で即時、負荷は無視できる。
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { _ in
            Task { @MainActor in ClipboardHistory.shared.poll() }
        }
    }

    private func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if let types = pb.types, types.contains(where: { Self.excludedTypes.contains($0.rawValue) }) {
            return
        }
        guard let text = pb.string(forType: .string) else { return }
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        guard text.count <= Self.maxEntryLength else { return }
        record(text)
    }

    // MARK: - 操作 API（UI から呼ぶ）

    /// 履歴の項目をクリップボードへ戻す（＝「現在の剪贴板」にする）。
    /// その後ホットキーで入力できる。自分で書いた変更は再記録せず先頭へ移すだけ。
    func copyToPasteboard(_ entry: ClipEntry) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(entry.text, forType: .string)
        lastChangeCount = pb.changeCount
        moveToTop(entry)
    }

    /// 履歴の項目を直接キー入力する（クリップボードは変更しない）。
    func type(_ entry: ClipEntry, intervalMs: Int, keycodeMode: Bool) async {
        await Engine.typeText(entry.text, intervalMs: intervalMs, keycodeMode: keycodeMode)
    }

    func remove(_ entry: ClipEntry) {
        entries.removeAll { $0.id == entry.id }
        save()
    }

    func clear() {
        entries.removeAll()
        save()
    }

    // MARK: - 内部

    private func record(_ text: String) {
        // 同じ内容は重複させず先頭へ
        entries.removeAll { $0.text == text }
        entries.insert(ClipEntry(id: UUID(), text: text, copiedAt: Date()), at: 0)
        trimAndSave()
    }

    private func moveToTop(_ entry: ClipEntry) {
        guard let idx = entries.firstIndex(where: { $0.id == entry.id }), idx != 0 else { return }
        let e = entries.remove(at: idx)
        entries.insert(e, at: 0)
        save()
    }

    private func trimAndSave() {
        if entries.count > maxEntries {
            entries.removeLast(entries.count - maxEntries)
        }
        save()
    }

    // MARK: - 永続化

    /// ~/Library/Application Support/Cliptype/history.json
    private static var fileURL: URL? {
        guard let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
        else { return nil }
        return base.appendingPathComponent("Cliptype", isDirectory: true)
            .appendingPathComponent("history.json")
    }

    private func load() {
        guard let url = Self.fileURL, let data = try? Data(contentsOf: url) else { return }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        entries = (try? decoder.decode([ClipEntry].self, from: data)) ?? []
    }

    private func save() {
        guard let url = Self.fileURL else { return }
        let dir = url.deletingLastPathComponent()
        do {
            try FileManager.default.createDirectory(
                at: dir, withIntermediateDirectories: true,
                attributes: [.posixPermissions: 0o700])
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            let data = try encoder.encode(entries)
            try data.write(to: url, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        } catch {
            // 内容は出さない。失敗しても常駐は続ける。
            NSLog("cliptype: failed to save clipboard history: %@", error.localizedDescription)
        }
    }
}
